// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAQ93i3hG-BCPrFtjxmNVrfhXnkxN0vcM',
    appId: '1:566512400109:web:e37d7acb45273402f0bee4',
    messagingSenderId: '566512400109',
    projectId: 'smarthome-6f0f0',
    authDomain: 'smarthome-6f0f0.firebaseapp.com',
    storageBucket: 'smarthome-6f0f0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw7ZlpxyxmSYaKdpPQ8jvbiMv3B-Bb7TE',
    appId: '1:566512400109:android:fadc652073527a97f0bee4',
    messagingSenderId: '566512400109',
    projectId: 'smarthome-6f0f0',
    storageBucket: 'smarthome-6f0f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnS4BrUFQfBGlN0nnq-DkaEB-EuzV8bhA',
    appId: '1:566512400109:ios:c0a38a13b61fb4b5f0bee4',
    messagingSenderId: '566512400109',
    projectId: 'smarthome-6f0f0',
    storageBucket: 'smarthome-6f0f0.appspot.com',
    androidClientId: '566512400109-fg3dp8h5bungmg6hccng6nm6moem76q9.apps.googleusercontent.com',
    iosClientId: '566512400109-2cvh7nsmh1d74biravdbns3288224932.apps.googleusercontent.com',
    iosBundleId: 'com.birigu.smarthomeuione',
  );
}
